include:
  - path: include/include.yaml
    project_directory: include

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ${HOST_DATA_PATH}/mysql:/var/lib/mysql
    restart: always
    command: --max_allowed_packet=1073741824 --wait_timeout=28800 --default-authentication-plugin=caching_sha2_password --log_bin_trust_function_creators=1 --expire-logs-days=7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 2s
      retries: 0
      start_period: 5s
    networks:
      - internal-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --cleanup --schedule "0 0 0 * * *"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  internal-network:
    internal: true
  public-network:
