[[tls.certificates]]
   certFile = "/configuration/{{domain_suffix}}.crt"
   keyFile = "/configuration/{{domain_suffix}}.key"

[tls.stores]
  [tls.stores.default]
   [tls.stores.default.defaultCertificate]
     certFile = "/configuration/{{domain_suffix}}.crt"
     keyFile = "/configuration/{{domain_suffix}}.key"

[tls.options]
  # Valid constants: https://pkg.go.dev/crypto/tls#pkg-constants
  [tls.options.default]
    minVersion = "VersionTLS12"
      cipherSuites = [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305", "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      ]
    [tls.options.mintls12]
      minVersion = "VersionTLS12"
