domain_suffix: simplifier.io
instances:
  develop:
    instance_name: develop
    db_password: develop_pass
    simplifier_subdomain: develop
    exposed_debugging_port: 2985
  production:
    instance_name: prod
    db_password: prod_pass
    simplifier_subdomain: prod
    exposed_debugging_port: 2986

