domain_suffix: simplifier.io
instances:
  develop:
    instance_name: develop
    db_password: develop_pass
    simplifier_subdomain: develop
    exposed_debugging_port: 2985
  production:
    instance_name: prod
    db_password: prod_pass
    simplifier_subdomain: prod
    exposed_debugging_port: 2986
secure:
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDJRUYU7dz8T7rI
    MidJoaUxipOgKhdv+SyxPv7d4Sah2L1ZRqbYFvL4Z88g+4vsc3qtaRV/OgFFXt81
    Xu+IfMoO75lrMP4Z6fBPTUo2zpFkHmq7uETcASBUuWeKHDQzK6xaEG9qJ/qZl6fW
    du4dsD+NNPCWK928hS4bB1FUU2JKSACBhzOrmi8sJih/4u9E5tSXeSQk4LeG3DAf
    MX/EAhpyZn+DSriLKhjgMv+409Ogd/xVwTvD9i6yrUJK9X4zUvDn9bqSAPqbU1PE
    IRldm+OAZbXnMtL5cjcLCrgjm04I8OwAix0JBJMpZLqys7XZi/35+XSsqECjBIxP
    dPQWj56XsOph3VGqkwHbSDngnDAOTg6uZdvNJo+MBVcPvl+uGEEscMNYANkbGRr2
    /hPEnasAb9R7PuGuVc0m4oYsSzTaAJfYBWfAtqDWi1IEnl22Smor0K80YLCgGci2
    E16842qtCPcBG22QXr7zqRJcWYfnCZt2NzKNBMKtsKRQ7oxl+gc4ksNdsdlWT/MU
    56A+IyLlsQKUhfwhXtm0mbJUF5TPC7B/2UvtRZNYcjdAnz1hsu/L71HqxiYgtyHW
    2gRoGERPAnN/FeJct8ynwvA/M8TSu4E14H3QVCQjaSDjmpYV37tRkcLEO9EI1kAR
    WX0KXaGPSDFAiCgeNRc/OGZDrnqnXwIDAQABAoICAAUuepNnXEN5BsuVa8JPHjwC
    rH8SSYnHotYdU3c0dXrzlxki4uce3O2p0bQW31wcmcS4UKYp2oaF3r4DZ6wRdyvT
    RBV1kwhPwX2iwicoqKcoyug/FWa+Kke3TjcVnf82cwV09ULvLI08hKs8yWLyR3CQ
    zSQDyEpmLPDjmCOeBSKS0yocG1rVNiNI1QB8P/Su8wiQEdVXnUhXh6JsWWgbNcF9
    0G9gD3tlstlyw3dndkQXUrCFsDUA5xeqf9Gcm4pVHeaa3Bn0jhizMhQTVhFweSoa
    p26Z6SlXpQGGKrkGWO5Z/xMBTqOnMbKxgsaLyEHr6YONLISVZrSYe8dzF1jNWCPV
    fW6Xoa1TgUZzpNWxFI/WToT/qT9W07fFbDkyA58ZAORh6O1kZH5/hvexmuj3cy5E
    Y5DiasV67SGrzkFEwajsPDqMfVRPvRk7Bkuyg21w9mjLM072Dh3gD8WcuO00dnpF
    Yg5Uy7M433RUht9hkCNyDVp2L/Sv6UqjJB2b0+Xwqr7Fdj70UhaOpQt31FLLPxlw
    Jwse4fA3+IryX00Ue7z/GdH81W8eUKAUxzlSJIQ1Fjov4/Z/9Exvvo5OeW27G8BB
    /fH4VoGpwtpdttSehIyaJHQeVVeGGzFm3EKTC4uwsBho56JcldY18XmEu4vHCNs6
    EP2p2eEeoMeVSfoJczRBAoIBAQDxJ9BbeBGM3fOyvIXVil20ZlHMBErafkw70lN/
    dqhYROrfZzzEKu/m64SiM6xM+Ygbc+9nAqyQr5QegK7r3uRgu6mk7eRrTrKdcWtn
    8uUu2e22o7B7hevQGZrRKRxjvAPi5Kcdx7VD4tfSERvI5sEnFkURdELto49FELUH
    4O8mugn0UXAzEO2kx8O4Fx469GCRzGiwzlu+9RSQEU7vEfmXdDc5DJjkW23PGOrw
    5JeZXG8LkEAd58ntBogRnewti4ZEWgn2oKQMo4jQR2aHbuCDLlkeuPbTRcxaA6/0
    iaC727E8CLDe6Fj/NBB7FLtOXUEqr2XS8OftnONM5kIrpKD3AoIBAQDVqPGaklIy
    5o0iZ2ySWkrPEszLJbX+43UF+AR+g2BUUZ83NxGRmyiFt+E3q/61ipv155NPm8aE
    /gtHnQ6yxKZv3B91fnkVFz5AP3jsQ0CZ03dFulhan/jnWvnNibJfzmmvjP5G5hDK
    lSi1n6xJ0FW9+9P+aX2y6/5PHnsDsd9AcY+x9HltJTIOR4Wc0DjbJil3/fWGPVL9
    m5gw2/mJvMChctzrWcx3l5FzCMYeWUhW3pwsgPhbGpe5RAZIBAKSfkBn8kGNKKfB
    asVHsKAGWN8eTv/HQJ9xpbpneP5YSJ0KSz/NxP16+3D/B7cYocSIT/qlD40TeryT
    LS/oWaEY6/rZAoIBAQCnvu0VIzD6Ds3cj3x87JF/0gil5Hp4/49hsUz5hf1V4SKL
    odFIFyHnO/53oYABzzVY+00VF2wX/LoIebSzR8kObJt1qTDRX92o3OM8XF4FN/w9
    piE12xMMHzNsuK8RxQ/i/PAuK+OvxBQiAFqWZcUHvlru6DNCABrBjPyP7WwNQS15
    cEiejPDxRS+kVxhlI+YkpM5R5kk1TF8wU4nXjGZUbreXDGcxuVNp0khipm+5cu2f
    WojvBHOWV4vAzVwi1kHgO81ga5+RVxPs5S2xmXO8bDn7v+eZUJz0JEp5zF4tLoVb
    YCQ/+dkmM/4ez2329bFF0tn+YCrEQvRtYmG23/5DAoIBAHmacgf7h3UY6vLN0mlp
    onJAzPZCPFcZthzzj/tBYq4a1ndijElG+cVBZpl89rb0cNeAOcNxcYd334uexCLS
    8bdwnScOGHP8ip2egoBVtorWZGf3KxpJOizTBqII4NDOdjBIGuDXSG9EfasBedl5
    DZPXpEyEVdpjnpYBTxpHPj07ZQFvlzybkuW1p0Ic8H8qNSfqDrecZ4OX7wK/8EKI
    f0pkSYBZ15mpVksWj0vunNF0WYaq0K9pbzkukjSis6QU3ytKIizpGrFmx2mKCUoT
    gsmJROJu0VCpdnI11u0ARwD42xOOLoa0XReJmJgYWfcLLiiLtUuE65cIfN/NQ3cf
    t+ECggEBAMK1PTT01RAq1jjhk/kh/FUoV648CdGS554PnF8TmJGk/MWWPeW/0d7P
    /r9RQA+OcBwY/g8gwOcYkEnHuI2CQ13Tn30HN0g4yh5XRHQMlBLhZaIao8OJbTvk
    D/wyS8SVQqTOysjFKj2qs+gpdZhQtpoE9TZ33ZV1YR7ATDa06jy2m17DHPBcc61G
    GhqOD8lRP/S4KUtpL/sUj6jkUb2tfKOwIuUkF2z4hAr5O5du3qyGXecKIVSoMhLd
    EGSHg0L+eZI033VHadPB8J34hrSTPBLe+QR2836GQEq6vPa1n+qg5NYWG2WAyijZ
    rNOljY62NmA4Rj2HKff+2s7oq6TDvqY=
    -----END PRIVATE KEY-----
  wildcard_crt_for_domain_suffix: |
    -----BEGIN CERTIFICATE-----
    MIIF5zCCA8+gAwIBAgIUfUoj3t0Ey6RK4DVr+wuKQyh9i+0wDQYJKoZIhvcNAQEL
    BQAwgYExCzAJBgNVBAYTAlhYMRIwEAYDVQQIDAlTdGF0ZU5hbWUxETAPBgNVBAcM
    CENpdHlOYW1lMRQwEgYDVQQKDAtDb21wYW55TmFtZTEbMBkGA1UECwwSQ29tcGFu
    eVNlY3Rpb25OYW1lMRgwFgYDVQQDDA8qLnNpbXBsaWZpZXIuaW8wIBcNMjQwOTA0
    MjA1MzE0WhgPMjEyNDA4MTEyMDUzMTRaMIGBMQswCQYDVQQGEwJYWDESMBAGA1UE
    CAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UECgwLQ29tcGFu
    eU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTEYMBYGA1UEAwwPKi5z
    aW1wbGlmaWVyLmlvMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyUVG
    FO3c/E+6yDInSaGlMYqToCoXb/kssT7+3eEmodi9WUam2Bby+GfPIPuL7HN6rWkV
    fzoBRV7fNV7viHzKDu+ZazD+GenwT01KNs6RZB5qu7hE3AEgVLlnihw0MyusWhBv
    aif6mZen1nbuHbA/jTTwlivdvIUuGwdRVFNiSkgAgYczq5ovLCYof+LvRObUl3kk
    JOC3htwwHzF/xAIacmZ/g0q4iyoY4DL/uNPToHf8VcE7w/Yusq1CSvV+M1Lw5/W6
    kgD6m1NTxCEZXZvjgGW15zLS+XI3Cwq4I5tOCPDsAIsdCQSTKWS6srO12Yv9+fl0
    rKhAowSMT3T0Fo+el7DqYd1RqpMB20g54JwwDk4OrmXbzSaPjAVXD75frhhBLHDD
    WADZGxka9v4TxJ2rAG/Uez7hrlXNJuKGLEs02gCX2AVnwLag1otSBJ5dtkpqK9Cv
    NGCwoBnIthNevONqrQj3ARttkF6+86kSXFmH5wmbdjcyjQTCrbCkUO6MZfoHOJLD
    XbHZVk/zFOegPiMi5bEClIX8IV7ZtJmyVBeUzwuwf9lL7UWTWHI3QJ89YbLvy+9R
    6sYmILch1toEaBhETwJzfxXiXLfMp8LwPzPE0ruBNeB90FQkI2kg45qWFd+7UZHC
    xDvRCNZAEVl9Cl2hj0gxQIgoHjUXPzhmQ656p18CAwEAAaNTMFEwHQYDVR0OBBYE
    FHblKv8vZHm/aku034NaPulmevIlMB8GA1UdIwQYMBaAFHblKv8vZHm/aku034Na
    PulmevIlMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAArZLJxG
    7x++91ssSJIBQPq9xrXoYOXGZp9fBheiUAYVdsWuqX3ar9A1AKWYjFmWZujXKt87
    oIB496EY1K/GbN5GMDaSWAQFXLyZKt+dm1/ZhCaxbXiyGm0xYp/vIKjrzVsLWqGO
    3S7FedXRou68732z0e+AeWV+8RnCzEsh/7rAXi501u2fF+78fYPGG2kmnI4NY2DB
    lH4kxH54F6OHQbMrm2yRWRLPqzVrPZtuFIgBA6UxQ2yZY8UONrxk9fyFwW+tW2za
    byX5ctmSs0a2mIaAlUacXhV0ivd6HR/OJ4bzEorGcyT01PHbGQi+H8j9T5UYtPh+
    FbmAHpgENRWTGYSMRlaJunkYMz4rW7yO4dA4+L9bFNgyDtqgDC7lBqDBkCMs10kQ
    2GXNAruy+dBzMEVhQWUXn29eAlwLlbPHFPb7MQRWxF/4Dt+jwfDBZ+lhqWwbQxUG
    1RcUVGxjsDlvYjzSkcpr6oTLgZJ+SG8wfkqOeJRnOZxX2mvPYcrDxc2mKaqlFl0X
    GGMfYQ5h18EYqeYpfoFbhTRB3aF6wVoLfSRcqfVOps8gtD3S4QqkV6Avz7MBTyjR
    wRf7nAHfyJCybe6mehKplyyHT0dc6cSMvG3UnEXATmyzifTKYCVnfofBzZAvn4/L
    FmGFZfMxpv7GJQf2f7HzWG7VkfMXFIH5zJWY
    -----END CERTIFICATE-----